// Scans the local portrait folder trees (which mirror the S3 buckets) and emits
// static catalog modules, so the app runs on GitHub Pages with no server.
import { readdirSync, existsSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const readDirs = (dir) => {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith('.'))
    .map((d) => d.name)
    .sort((a, b) => a.localeCompare(b));
};

const buildCatalog = (game) => {
  const base = join(root, 'generators', game, 'images', 'portraits');
  const catalog = {};
  for (const char of readDirs(base)) {
    const emotions = readDirs(join(base, char));
    if (!emotions.length) continue;
    catalog[char] = {};
    for (const emote of emotions) {
      const costumes = readDirs(join(base, char, emote));
      if (costumes.length) catalog[char][emote] = costumes;
    }
    if (!Object.keys(catalog[char]).length) delete catalog[char];
  }
  return catalog;
};

for (const game of ['P5', 'P4']) {
  const catalog = buildCatalog(game);
  const chars = Object.keys(catalog);
  const combos = chars.reduce(
    (n, c) => n + Object.values(catalog[c]).reduce((m, list) => m + list.length, 0),
    0,
  );
  const outDir = join(root, 'src', 'data');
  mkdirSync(outDir, { recursive: true });
  const out = join(outDir, game === 'P5' ? 'catalogP5.ts' : 'catalogP4.ts');
  writeFileSync(
    out,
    `// Auto-generated by scripts/generate-catalog.mjs. Do not edit by hand.\n` +
      `const catalog: Record<string, Record<string, string[]>> = ${JSON.stringify(catalog)};\n\n` +
      `export default catalog;\n`,
  );
  console.log(`${game}: ${chars.length} characters, ${combos} portrait combos -> ${out}`);
}
